# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etymology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etymology', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=200)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Definition')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('lookup_date', models.DateTimeField(verbose_name='date looked up')),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='etymology',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word'),
        ),
        migrations.AddField(
            model_name='definition',
            name='etymology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Etymology'),
        ),
        migrations.AddField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word'),
        ),
    ]
