# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20180805_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('-lookup_date',)},
        ),
        migrations.AddField(
            model_name='word',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_word_translations_+', to='words.Word'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='etymology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='words.Etymology'),
        ),
        migrations.AlterField(
            model_name='definition',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_definitions', to='words.Word'),
        ),
        migrations.AlterField(
            model_name='etymology',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etymologies', to='words.Word'),
        ),
        migrations.AlterField(
            model_name='example',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='words.Definition'),
        ),
        migrations.AlterField(
            model_name='word',
            name='language',
            field=models.CharField(max_length=33),
        ),
    ]
