# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-02 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20180827_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('created_date', models.DateTimeField(verbose_name='date created')),
                ('notes', models.CharField(max_length=200)),
                ('words', models.ManyToManyField(blank=True, related_name='words', to='words.Word')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.AddField(
            model_name='example',
            name='word',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='word_examples', to='words.Word'),
            preserve_default=False,
        ),
    ]
