# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 21:02
from __future__ import unicode_literals

from django.db import migrations
import sortedm2m.fields


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20180913_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='words',
            field=sortedm2m.fields.SortedManyToManyField(help_text=None, related_name='words', to='words.Word'),
        ),
    ]
