# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_auto_20180914_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='etymology',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='words.Etymology'),
        ),
    ]
