# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-16 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_auto_20180914_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='definition',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='etymology',
            name='etymology',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
