# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0014_word_from_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='from_translation',
            field=models.BooleanField(default=False),
        ),
    ]
