# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0016_auto_20180920_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionOfWords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='words',
        ),
        migrations.AddField(
            model_name='collection',
            name='words',
            field=models.ManyToManyField(related_name='words', through='words.CollectionOfWords', to='words.Word'),
        ),
        migrations.AddField(
            model_name='collectionofwords',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Collection'),
        ),
        migrations.AddField(
            model_name='collectionofwords',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word'),
        ),
    ]
