# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0017_auto_20180926_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='synonyms',
            field=models.ManyToManyField(blank=True, related_name='_word_synonyms_+', to='words.Word'),
        ),
    ]
