# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0018_word_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='definition',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='etymology',
            name='etymology',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
