# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0022_auto_20181002_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=200),
        ),
    ]
