# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0023_auto_20181002_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collocation',
            name='example',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='collocation',
            name='expression',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='collocation',
            name='translation',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='example',
            name='example',
            field=models.CharField(max_length=600),
        ),
    ]
