# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0024_auto_20181003_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=400),
        ),
    ]
