# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0031_word_pronounce'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_verb',
            field=models.BooleanField(default=False),
        ),
    ]
