# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-30 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0032_word_is_verb'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='conjugations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='origin_verb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verb', to='words.Word'),
        ),
    ]
