# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0033_auto_20181130_0824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionofwords',
            options={'ordering': ('-date_added',)},
        ),
        migrations.AlterField(
            model_name='word',
            name='notes',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=600),
        ),
    ]
