# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0035_auto_20181219_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordnote',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_notes', to='words.Word'),
        ),
    ]
