# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0036_auto_20181221_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('collectionofwords', '-lookup_date')},
        ),
    ]
