# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0037_auto_20190206_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='did_conjugations',
            field=models.BooleanField(default=False),
        ),
    ]
