# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0038_word_did_conjugations'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='did_book_examples',
            field=models.BooleanField(default=False),
        ),
    ]
