# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0039_word_did_book_examples'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=33)),
                ('num_id', models.IntegerField()),
            ],
            options={
                'ordering': ('num_id',),
            },
        ),
    ]
