# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0041_lookupmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookupmap',
            name='word',
            field=models.CharField(max_length=60),
        ),
    ]
