# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 23:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0042_auto_20190709_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationsMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=60)),
                ('lookup_date', models.DateTimeField(verbose_name='date looked up')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Language')),
            ],
            options={
                'ordering': ('-lookup_date',),
            },
        ),
    ]
