# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-11 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0044_auto_20190917_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='definition',
            field=models.TextField(null=True),
        ),
    ]
