# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-12 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0045_auto_20200311_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='origin_word',
            field=models.ManyToManyField(blank=True, null=True, related_name='_word_origin_word_+', to='words.Word'),
        ),
        migrations.AlterField(
            model_name='inflections',
            name='inflections',
            field=models.CharField(max_length=500),
        ),
    ]
