# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-13 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0046_auto_20200312_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='did_inflections',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='origin_word',
            field=models.ManyToManyField(blank=True, related_name='_word_origin_word_+', to='words.Word'),
        ),
    ]
