# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0047_auto_20200313_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='origin_word',
            field=models.ManyToManyField(blank=True, related_name='original_word', to='words.Word'),
        ),
    ]
