# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-13 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0048_auto_20200313_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflections',
            name='inflections',
            field=models.CharField(max_length=900),
        ),
    ]
