export const FETCH_VERBS = 'FETCH_VERBS';
export const FETCH_VERB = 'FETCH_VERB';
export const FETCH_VERBS_FULFILLED = 'FETCH_VERBS_FULFILLED';
export const FETCH_VERB_FULFILLED = 'FETCH_VERB_FULFILLED';
export const FETCH_VERBS_REJECTED =  'FETCH_VERBS_REJECTED';
export const FETCH_VERB_REJECTED =  'FETCH_VERB_REJECTED';

export const FETCH_CONJUGATIONS = 'FETCH_CONJUGATIONS';
export const FETCH_CONJUGATIONS_FULFILLED = 'FETCH_CONJUGATIONS_FULFILLED';
export const FETCH_CONJUGATIONS_REJECTED =  'FETCH_CONJUGATIONS_REJECTED';
export const LOG_CONJUGATE_REFS =  'LOG_CONJUGATE_REFS';
export const STORE_MY_CONJUGATIONS =  'STORE_MY_CONJUGATIONS';
export const LOG_TENSE_IDX =  'LOG_TENSE_IDX';

export const FETCH_HOMEWORK = 'FETCH_HOMEWORK';
export const FETCH_HOMEWORK_FULFILLED = 'FETCH_HOMEWORK_FULFILLED';
export const FETCH_HOMEWORK_REJECTED =  'FETCH_HOMEWORK_REJECTED';
export const LOG_HOMEWORK_REFS =  'LOG_HOMEWORK_REFS';
export const STORE_MY_HOMEWORK_CONJUGATIONS =  'STORE_MY_HOMEWORK_CONJUGATIONS';
export const LOG_HOMEWORK_TENSE_IDX =  'LOG_HOMEWORK_TENSE_IDX';
