export const FETCH_VERBS = 'FETCH_VERBS';
export const FETCH_VERB = 'FETCH_VERB';
export const FETCH_VERBS_FULFILLED = 'FETCH_VERBS_FULFILLED';
export const FETCH_VERB_FULFILLED = 'FETCH_VERB_FULFILLED';
export const FETCH_VERBS_REJECTED =  'FETCH_VERBS_REJECTED';
export const FETCH_VERB_REJECTED =  'FETCH_VERB_REJECTED';

export const FETCH_CONJUGATIONS = 'FETCH_CONJUGATIONS';
export const FETCH_CONJUGATIONS_FULFILLED = 'FETCH_CONJUGATIONS_FULFILLED';
export const FETCH_CONJUGATIONS_REJECTED =  'FETCH_CONJUGATIONS_REJECTED';
export const LOG_CONJUGATE_REFS =  'LOG_CONJUGATE_REFS';
export const STORE_MY_CONJUGATIONS =  'STORE_MY_CONJUGATIONS';
export const LOG_TENSE_IDX =  'LOG_TENSE_IDX';

export const FETCH_HOMEWORK = 'FETCH_HOMEWORK';
export const FETCH_HOMEWORK_FULFILLED = 'FETCH_HOMEWORK_FULFILLED';
export const FETCH_HOMEWORK_REJECTED =  'FETCH_HOMEWORK_REJECTED';
export const LOG_HOMEWORK_REFS =  'LOG_HOMEWORK_REFS';
export const STORE_MY_HOMEWORK_CONJUGATIONS =  'STORE_MY_HOMEWORK_CONJUGATIONS';
export const LOG_HOMEWORK_TENSE_IDX =  'LOG_HOMEWORK_TENSE_IDX';

export const CLEAR_NEW_WORD_ERROR = 'CLEAR_NEW_WORD_ERROR';
export const FETCH_WORD = 'FETCH_WORD';
export const REGISTER_UUID = 'REGISTER_UUID';
export const FETCH_WORD_FULFILLED = 'FETCH_WORD_FULFILLED';
export const FETCH_WORD_REJECTED =  'FETCH_WORD_REJECTED';

export const FETCH_SYNONYMS_FULFILLED = 'FETCH_SYNONYMS_FULFILLED';
export const FETCH_SYNONYMS_REJECTED =  'FETCH_SYNONYMS_REJECTED';
export const FETCH_SYNONYMS = 'FETCH_SYNONYMS';

export const FETCH_NOTE_FULFILLED = 'FETCH_NOTE_FULFILLED';
export const FETCH_NOTE_REJECTED =  'FETCH_NOTE_REJECTED';
export const FETCH_NOTE = 'FETCH_NOTE';

export const FETCH_TENSES_FULFILLED = 'FETCH_TENSES_FULFILLED';
export const FETCH_TENSES_REJECTED =  'FETCH_TENSES_REJECTED';
