# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0037_auto_20190206_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conjugation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_form', models.CharField(max_length=33)),
            ],
            options={
                'ordering': ('pronoun',),
            },
        ),
        migrations.CreateModel(
            name='ConjugationExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example', models.CharField(max_length=500)),
                ('is_bad', models.BooleanField(default=False)),
                ('conjugation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conjugation', to='homework.Conjugation')),
            ],
        ),
        migrations.CreateModel(
            name='Pronoun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronoun', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=33)),
                ('num_id', models.IntegerField()),
            ],
            options={
                'ordering': ('num_id',),
            },
        ),
        migrations.CreateModel(
            name='Tense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=33)),
                ('num_id', models.IntegerField()),
            ],
            options={
                'ordering': ('num_id',),
            },
        ),
        migrations.AddField(
            model_name='conjugation',
            name='pronoun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_pronoun', to='homework.Pronoun'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='tense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tense', to='homework.Tense'),
        ),
        migrations.AddField(
            model_name='conjugation',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_word', to='words.Word'),
        ),
    ]
