# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tense',
            old_name='name',
            new_name='tense',
        ),
        migrations.AlterField(
            model_name='conjugation',
            name='tense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verb_tense', to='homework.Tense'),
        ),
    ]
