# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-08 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_auto_20190208_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conjugationexample',
            name='example',
            field=models.TextField(),
        ),
    ]
