# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0037_auto_20190206_1442'),
        ('homework', '0004_auto_20190208_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjugationexample',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conjugation_word', to='words.Word'),
            preserve_default=False,
        ),
    ]
