# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_conjugationexample_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='conjugationexample',
            name='tense',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conjugation_tense', to='homework.Tense'),
            preserve_default=False,
        ),
    ]
