export const CLEAR_ERROR = 'CLEAR_ERROR';

export const FETCH_WORDS = 'FETCH_WORDS';
export const FETCH_WORDS_FULFILLED = 'FETCH_WORDS_FULFILLED';
export const FETCH_WORDS_REJECTED =  'FETCH_WORDS_REJECTED';

export const FETCH_TRANSLATION_FULFILLED = 'FETCH_TRANSLATION_FULFILLED';
export const FETCH_TRANSLATION_REJECTED =  'FETCH_TRANSLATION_REJECTED';
export const FETCH_TRANSLATION = 'FETCH_TRANSLATION';

export const FETCH_WORD_FULFILLED = 'FETCH_WORD_FULFILLED';
export const FETCH_WORD = 'FETCH_WORD';

export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const FETCH_COLLECTION = 'FETCH_COLLECTION';
export const FETCH_COLLECTION_REJECTED = 'FETCH_COLLECTION_REJECTED';
export const FETCH_COLLECTIONS_FULFILLED = 'FETCH_COLLECTIONS_FULFILLED';
export const FETCH_COLLECTION_FULFILLED = 'FETCH_COLLECTION_FULFILLED';
export const SAVE_COLLECTION = 'SAVE_COLLECTION';
export const SAVE_COLLECTION_FULFILLED = 'SAVE_COLLECTION_FULFILLED';
export const SAVE_COLLECTION_REJECTED= 'SAVE_COLLECTION_REJECTED';

export const SWITCH_TAB = 'SWITCH_TAB';
