export const FETCH_WORDS = 'FETCH_WORDS';
export const FETCH_WORDS_FULFILLED = 'FETCH_WORDS_FULFILLED';
export const FETCH_WORDS_REJECTED =  'FETCH_WORDS_REJECTED';

export const FETCH_PRONOUNCE_FULFILLED = 'FETCH_PRONOUNCE_FULFILLED';
export const FETCH_PRONOUNCE_REJECTED =  'FETCH_PRONOUNCE_REJECTED';
export const FETCH_PRONOUNCE = 'FETCH_PRONOUNCE';

export const FETCH_CONJUGATE_FULFILLED = 'FETCH_CONJUGATE_FULFILLED';
export const FETCH_CONJUGATE_REJECTED =  'FETCH_CONJUGATE_REJECTED';
export const FETCH_CONJUGATE = 'FETCH_CONJUGATE';

export const FETCH_SYNONYMS_FULFILLED = 'FETCH_SYNONYMS_FULFILLED';
export const FETCH_SYNONYMS_REJECTED =  'FETCH_SYNONYMS_REJECTED';
export const FETCH_SYNONYMS = 'FETCH_SYNONYMS';

export const FETCH_TRANSLATION_FULFILLED = 'FETCH_TRANSLATION_FULFILLED';
export const FETCH_TRANSLATION_REJECTED =  'FETCH_TRANSLATION_REJECTED';
export const FETCH_TRANSLATION = 'FETCH_TRANSLATION';

export const FETCH_NOTE_FULFILLED = 'FETCH_NOTE_FULFILLED';
export const FETCH_NOTE_REJECTED =  'FETCH_NOTE_REJECTED';
export const FETCH_NOTE = 'FETCH_NOTE';

export const FETCH_COLLOCATIONS_FULFILLED = 'FETCH_COLLOCATIONS_FULFILLED';
export const FETCH_COLLOCATIONS_REJECTED =  'FETCH_COLLOCATIONS_REJECTED';
export const FETCH_COLLOCATIONS = 'FETCH_COLLOCATIONS';

export const FETCH_WORD_FULFILLED = 'FETCH_WORD_FULFILLED';
export const FETCH_WORD = 'FETCH_WORD';
export const CLEAR_NEW_WORD_ERROR = 'CLEAR_NEW_WORD_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const FETCH_COLLECTIONS = 'FETCH_COLLECTIONS';
export const FETCH_COLLECTION = 'FETCH_COLLECTION';
export const FETCH_COLLECTION_REJECTED = 'FETCH_COLLECTION_REJECTED';
export const FETCH_COLLECTIONS_FULFILLED = 'FETCH_COLLECTIONS_FULFILLED';
export const FETCH_COLLECTION_FULFILLED = 'FETCH_COLLECTION_FULFILLED';
export const SAVE_COLLECTION = 'SAVE_COLLECTION';
export const SAVE_COLLECTION_FULFILLED = 'SAVE_COLLECTION_FULFILLED';
export const SAVE_COLLECTION_REJECTED = 'SAVE_COLLECTION_REJECTED';
export const CLEAR_FETCHED = 'CLEAR_FETCHED';
export const CLEAR_FETCHING = 'CLEAR_FETCHING';
export const CLEAR_FETCHED_NOTE = 'CLEAR_FETCHED_NOTE';

export const SWITCH_TAB = 'SWITCH_TAB';
export const MAP_REF = 'MAP_REF';
export const SET_ALL_DATA_REF = 'SET_ALL_DATA_REF';
export const MAP_OFFSET  = 'MAP_OFFSET';

export const SWITCH_VISIBILITY = 'SWITCH_VISIBILITY';
