export const FETCH_WORDS = 'FETCH_WORDS';
export const FETCH_WORDS_FULFILLED = 'FETCH_WORDS_FULFILLED';
export const FETCH_WORD_FULFILLED = 'FETCH_WORD_FULFILLED';
export const FETCH_WORDS_REJECTED =  'FETCH_WORDS_REJECTED';
export const FETCH_WORD = 'FETCH_WORD';
export const FETCH_TRANSLATION = 'FETCH_TRANSLATION';
export const SWITCH_TAB = 'SWITCH_TAB';
