# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-25 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0050_auto_20200313_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('work', models.TextField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('lesson_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Collection')),
            ],
        ),
    ]
